### PR TITLE
install.sh: remove dependency for `which` command

### LINKED ISSUE #574: install script fails on amazonlinx2 inside docker (Giving incorrect wrong version of git error)
**Bug: `which` dependency is not made clear, resulting in a misleading error message.**

When I try to install homebrew on amazonlinux2 it fails telling me that my version of git is too old, this error is actually caused by the lack of "which" command on the default install.

This took me a while to figure out, so it would be nice if the install script would give a more meaningful error telling me that I need to install "which" first.

Here is the dockerfile to reproduce the issue:

```dockerfile
FROM amazonlinux:2

# Install git and other dev tools
RUN yum update -y && yum install -y initscripts;
RUN yum groupinstall -y 'Development Tools'

### create test user (brew doesn't like to be run from root)
RUN useradd -ou 0 -g 0 admin
RUN usermod -G root admin
RUN su - admin
RUN mkdir .ssh
RUN chmod 700 .ssh
RUN touch .ssh/authorized_keys
RUN chmod 600 .ssh/authorized_keys
ENV HOME="/home/admin"

# install ruby
RUN yum install -y git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel
RUN git clone git://github.com/sstephenson/rbenv.git $HOME/.rbenv
RUN git clone git://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build
RUN echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> $HOME/.profile
ENV PATH="$HOME/.rbenv/bin:$HOME/.rbenv/plugins/ruby-build/bin:$HOME/.rbenv/shims:/bin:${PATH}"
RUN echo 'eval "$(rbenv init -)"' >> $HOME/.profile
RUN eval "$(rbenv init -)"
RUN . $HOME/.profile
RUN rbenv install -v 2.5.9
RUN rbenv global 2.5.9
RUN echo "gem: --no-document" > $HOME/.gemrc
RUN gem install bundler
RUN rbenv rehash

# install homebrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

and the fix was to add this line `RUN yum install -y which`

```dockerfile
FROM amazonlinux:2

# Install git and other dev tools
RUN yum update -y && yum install -y initscripts;
RUN yum groupinstall -y 'Development Tools'
RUN yum install -y which

### create test user (brew doesn't like to be run from root)
RUN useradd -ou 0 -g 0 admin
RUN usermod -G root admin
RUN su - admin
RUN mkdir .ssh
RUN chmod 700 .ssh
RUN touch .ssh/authorized_keys
RUN chmod 600 .ssh/authorized_keys
ENV HOME="/home/admin"

# install ruby
RUN yum install -y git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel
RUN git clone git://github.com/sstephenson/rbenv.git $HOME/.rbenv
RUN git clone git://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build
RUN echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> $HOME/.profile
ENV PATH="$HOME/.rbenv/bin:$HOME/.rbenv/plugins/ruby-build/bin:$HOME/.rbenv/shims:/bin:${PATH}"
RUN echo 'eval "$(rbenv init -)"' >> $HOME/.profile
RUN eval "$(rbenv init -)"
RUN . $HOME/.profile
RUN rbenv install -v 2.5.9
RUN rbenv global 2.5.9
RUN echo "gem: --no-document" > $HOME/.gemrc
RUN gem install bundler
RUN rbenv rehash

# install homebrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

The problem is here inside the install script `$(which -a "$1" 2>/dev/null)`
```bash
find_tool() {
  if [[ $# -ne 1 ]]; then
    return
  fi

  local executable
  IFS=$'\n' # Do word splitting on new lines only
  for executable in $(which -a "$1" 2>/dev/null); do
    if "test_$1" "$executable"; then
      echo "$executable"
      break
    fi
  done
  IFS=$' \t\n' # Restore IFS to its default value
}
```

### PR DESCRIPTION
**Pull request by XuehaiPan**
Remove `which` command, search executables under all entries in `PATH`. Closes #574.

BTW, `which` command shows both executable files and aliases.

```console
$ which -a python
/usr/bin/python

$ alias python='python3'

$ which -a python
python: aliased to python3
/usr/bin/python
```

We should never use `which` to find usable commands ([shellcheck SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230)), use `command -v` instead. However, I do not find a `which -a` equivalent for `command -v`. This PR enumerates all entries in `PATH`.

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -264,8 +264,7 @@ file_not_grpowned() {
 
 # Please sync with 'test_ruby()' in 'Library/Homebrew/utils/ruby.sh' from Homebrew/brew repository.
 test_ruby() {
-  if [[ ! -x $1 ]]
-  then
+  if [[ ! -x "$1" ]]; then
```
Comment (carlocab) [inline install.sh:267]: Putting then on the next line so that
```suggestion
  if [[ ! -x "$1" ]]
  then
```
is actually a lot more common throughout this script, I think.

File: install.sh [hunk 2]
```diff
@@ -295,21 +294,41 @@ test_git() {
...
+  local executable entries entry presented=''
+  IFS=':' read -r -a entries <<< "${PATH}"  # `readarray -d ':' -t` seems not applicable on WSL Bash
+  for entry in "${entries[@]}"; do
+    executable="${entry}/$1"
+    if [[ -x "${executable}" ]]; then
+      echo "${executable}"
+      presented='yes'
+    fi
+  done
+  if [[ -n "${presented}" ]]; then
```
Comment (carlocab) [inline install.sh:312]:
```suggestion
  local executable entries entry present=''
  IFS=':' read -r -a entries <<< "${PATH}"  # `readarray -d ':' -t` seems not applicable on WSL Bash
  for entry in "${entries[@]}"; do
    executable="${entry}/$1"
    if [[ -x "${executable}" ]]; then
      echo "${executable}"
      present='yes'
    fi
  done
  if [[ -n "${present}" ]]; then
```
Or, maybe use `available` instead of `present`.

**Review by carlocab — COMMENTED** [review]
Thanks @XuehaiPan!

File: install.sh (hunk 1 above)
Comment (XuehaiPan) [reply install.sh]: It seems that `then` and `do` are always put in the separated line in the main repo ([Homebrew/brew](https://github.com/Homebrew/brew)). And I will follow this code style for all shell scripts.

However, some `if ... then` and `for ... do` statements do not follow the above style in this repo ([Homebrew/install](https://github.com/Homebrew/install)). Besides, up to the present time, [`shfmt`](https://github.com/mvdan/sh) always put `then` and `do` combined with the previous line with a semicolon `;` (mvdan/sh#721 may introduce a new flag in the near future).

I think we can provide a git pre-commit hook or specify in the contributing guidelines for the code style. Something like `shfmt -i 2 -ci`: indent 2 spaces and indent switch cases (and a flag for wrapping `then / do`).

Comment (MikeMcQuaid) [reply install.sh]: > Something like `shfmt -i 2 -ci`: indent 2 spaces and indent switch cases (and a flag for wrapping `then / do`).

I'd be game for making `brew style` run `shfmt` and being consistent with usage in both Homebrew/brew and here 👍🏻

**Review by MikeMcQuaid — APPROVED** [review]
Looks good, thanks @XuehaiPan

**Comment by XuehaiPan** [comment]
> However, I do not find a `which -a` equivalent for `command -v`. This PR enumerates all entries in `PATH`.

I find out that we could use `bash`'s builtin command `type -aP execuable`, which also does an exhausted search but without a separated function.

**Comment by carlocab** [comment]
I did wonder briefly whether `type` might work. That seems much nicer.
