### PR TITLE
fix perms for /etc/paths.d/homebrew

### LINKED ISSUE #997: Homebrew path_helper file /etc/paths.d/homebrew has wrong permissions
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] you carefully read the output and it was not a `git fetch` or other connection issue to GitHub (that Homebrew has no control over)?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

```bash
% brew config
HOMEBREW_VERSION: 4.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: c19f08b3e8ea46ba94bd9315c46c0dda10ead31c
Last commit: 12 days ago
Branch: stable
Core tap JSON: 05 Jul 16:14 UTC
Core cask tap JSON: 05 Jul 16:14 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 14
Homebrew Ruby: 3.4.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.4/bin/ruby
CPU: 14-core 64-bit arm_brava
Clang: 17.0.0 build 1700
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.5-arm64
CLT: 16.4.0.0.1.1747106510
Xcode: N/A
Rosetta 2: false

% brew doctor
Your system is ready to brew.
```
## What you were trying to do (and why)

Use homebrew and installed tools as usual.

## What happened (include command output)

When opening any new shell, I got the following warning consistently:

```bash
path_helper: homebrew: Permission denied
```

Running `brew doctor` was something I tried but didn't fix it.

## What you expected to happen

No homebrew specific warning in every new shell.

## Step-by-step reproduction instructions (by running `brew` commands)

I installed homebrew with the from the website:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Open a new shell, for example in Terminal.app.

## Workaround fix

I was able to remove the warning by running
```bash
sudo chmod 644 /etc/paths.d/homebrew
```

## Workaround fix

I was able to remove the warning by running
```bash
sudo chmod 644 /etc/paths.d/homebrew
```

The homebrew path helper might get installed with too narrow permissions. For example the (probably preinstalled with macOS, since this is a new mac) `10-cryptex` helpter also has 644 permissions

```
% ls -hal
-rw-r--r--   1 root  wheel   224B May  4 07:39 10-cryptex
-rw-r-----   1 root  wheel    18B Jul  5 18:17 homebrew

% sudo chmod 644 /etc/paths.d/homebrew

% ls -hal
-rw-r--r--   1 root  wheel   224B May  4 07:39 10-cryptex
-rw-r--r--@  1 root  wheel    18B Jul  5 18:17 homebrew

### PR DESCRIPTION
**Pull request by gromgit**
Closes #997

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -1027,6 +1027,7 @@ then
   execute_sudo "${MKDIR[@]}" /etc/paths.d
   echo "${HOMEBREW_PREFIX}/bin" | execute_sudo tee /etc/paths.d/homebrew
   execute_sudo "${CHOWN[@]}" root:wheel /etc/paths.d/homebrew
+  execute_sudo "${CHMOD[@]}" "a+r" /etc/paths.d/homebrew
```
Comment (carlocab) [inline install.sh:1030]:
```suggestion
  execute_sudo "${CHMOD[@]}" 0644 /etc/paths.d/homebrew
```
So we're not at the mercy of the machine's `umask`?

**Review by carlocab — APPROVED** [review]
