### PR TITLE
install.sh: use `printf` to print post-install instructions

### LINKED ISSUE #880: brew install on Linux gives non-working fish profile commands
### `brew doctor` output

```shell
N/A
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
N/A
```

### What were you trying to do (and why)?

`(echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/justin-ksb/.config/fish/config.fish`

It's the command suggested by the installer to add brew to my PATH

### What happened (include all command output)?

fish: command substitutions not allowed here

### What did you expect to happen?

Added to fish profile successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Wait for install to finish, follow instructions given (below) to setup $PATH

- Run these two commands in your terminal to add Homebrew to your PATH:
    (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/justin-ksb/.config/fish/config.fish
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

```
```

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
In Fish shell, parentheses are for command substitution, so the parenthesised subshell used for `echo` grouping does not work there. Instead let's use `printf` to print the post-install instructions; it's more portable.

Fixes #880.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

File: install.sh [hunk 1]
```diff
@@ -1048,7 +1048,7 @@ EOS
 else
   cat <<EOS
 - Run these two commands in your terminal to add Homebrew to your ${tty_bold}PATH${tty_reset}:
-    (echo; echo 'eval "\$(${HOMEBREW_PREFIX}/bin/brew shellenv)"') >> ${shell_rcfile}
+    printf '%s\n' '' 'eval "\$(${HOMEBREW_PREFIX}/bin/brew shellenv)"' >> ${shell_rcfile}
```
Comment (carlocab) [inline install.sh:1051]: Wait, this will print
```
printf '%s\n' '' 'eval "\$(${HOMEBREW_PREFIX}/bin/brew shellenv)"'
```
but we want `${HOMEBREW_PREFIX}` to be expanded.

Comment (ZhongRuoyu) [reply install.sh:1051]: (Yes, I know it's a bit confusing, but) We're in a `cat <<EOS` context so single quotes don't really mean non-expansion. See https://github.com/Homebrew/install/actions/runs/11034527267/job/30649515010?pr=881#step:8:489.

Comment (carlocab) [reply install.sh:1051]: Right, yes, gotcha!

**Review by MikeMcQuaid — APPROVED** [review]
Seems fine, thanks @ZhongRuoyu. Ideally we'd make this Fish-specific but can be in a follow-up PR.
