### PR TITLE
Fix git outdated error saying git is not installed

### LINKED ISSUE #773: Install script CentOS 7 can't find git
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?
```
[osalbahr@vclvm177-222 ~]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[osalbahr@vclvm177-222 ~]$ uname -a
Linux vclvm177-222.vcl.ncsu.edu 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[osalbahr@vclvm177-222 ~]$ 
```

## What you were trying to do (and why)

I was trying to install Homebrew so I can `brew install neofetch`.

## What happened (include command output)

<details>
  <summary>You must install Git before installing Homebrew</summary>
  <pre>
[osalbahr@vclvm177-222 ~]$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm177-222 ~]$ 
  </pre>
</details>

## What you expected to happen

<details>
  <summary>I expected the install script to go through, since I do have git installed:</summary>
  <pre>
[osalbahr@vclvm177-222 ~]$ git --version
git version 1.8.3.1
[osalbahr@vclvm177-222 ~]$ which -a git
/usr/bin/git
[osalbahr@vclvm177-222 ~]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/osalbahr/.local/bin:/home/osalbahr/bin
[osalbahr@vclvm177-222 ~]$ sudo yum install -y git
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: linux-mirrors.fnal.gov
 * epel: forksystems.mm.fcix.net
 * extras: distro.ibiblio.org
 * updates: centos.mirror.constant.com
Package git-1.8.3.1-24.el7_9.x86_64 already installed and latest version
Nothing to do
[osalbahr@vclvm177-222 ~]$ sudo dnf install -y git
Last metadata expiration check: 0:03:10 ago on Wed 17 May 2023 11:12:33 AM CDT.
Package git-1.8.3.1-24.el7_9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[osalbahr@vclvm177-222 ~]$ 
  </pre>
</details>

<details>
  <summary>The same happens after `sudo yum update && sudo reboot` </summary>
  <pre>
[osalbahr@vclvm177-222 ~]$ sudo yum update
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: coresite.mm.fcix.net
 * epel: download-ib01.fedoraproject.org
 * extras: mirrors.lug.mtu.edu
 * updates: mirror.wdc2.us.leaseweb.net
No packages marked for update
[osalbahr@vclvm177-222 ~]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[osalbahr@vclvm177-222 ~]$ uname -a
Linux vclvm177-222.vcl.ncsu.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[osalbahr@vclvm177-222 ~]$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm177-222 ~]$ 
  </pre>
</details>

I'm not sure what [`find_tool`](https://github.com/Homebrew/install/blob/master/install.sh#L405) does.

#574 might be related. If this is a case of git version issue, the install script might benefit from a different error message.

## Step-by-step reproduction instructions (by running `brew` commands)

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

### PR DESCRIPTION
**Pull request by ChillerDragon**
Fixes #773

In https://github.com/Homebrew/install/pull/756 I introduced the bug of changing the error message "git is too old" into "git is not installed"

I tested this pr by uninstalling git and then running

```
echo -e '#!/bin/bash\necho git version 1.8.3.1' | sudo tee /usr/local/bin/git
sudo chmod +x /usr/local/bin/git
```

Before the pr it said

```
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
```

Now it says

```
The version of Git that was found does not satisfy requirements for Homebrew.
Please install Git 2.7.0 or newer and add it to your PATH.
```

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -844,16 +844,18 @@ EOABORT
...
     abort "$(
       cat <<EOABORT
 The version of Git that was found does not satisfy requirements for Homebrew.
 Please install Git ${REQUIRED_GIT_VERSION} or newer and add it to your PATH.
 EOABORT
     )"
-  elif [[ "${USABLE_GIT}" != /usr/bin/git ]]
+  fi
+  USABLE_GIT="${suitable_git}"
+  if [[ "${USABLE_GIT}" != /usr/bin/git ]]
```
Comment (osalbahr) [inline install.sh:858]: Is there a reason why you explicitly use `/usr/bin/git`?

Comment (ChillerDragon) [reply install.sh:858]: Don't think thats my code maybe @gromgit knows

Comment (ChillerDragon) [reply install.sh:858]: Oh wait yea I think its just about telling the user hey we found this git in path and going to use that.
But if we do use /usr/bin/git we just silently do that and assume the user does not care because its pretty standard.

**Review by MikeMcQuaid — APPROVED** [review]
Thanks @ChillerDragon!

**Comment by Bo98** [comment]
https://github.com/orgs/Homebrew/discussions/4518

**Comment by ChillerDragon** [comment]
> https://github.com/orgs/Homebrew/discussions/4518

Ah true I broke mac

**Comment by osalbahr** [comment]
> > https://github.com/orgs/Homebrew/discussions/4518
> 
> Ah true I broke mac

Is there not a GitHub Actions testing this?

**Comment by ChillerDragon** [comment]
> > > https://github.com/orgs/Homebrew/discussions/4518
> > 
> > 
> > Ah true I broke mac
> 
> Is there not a GitHub Actions testing this?

No it barley checks any edge cases. I tried [adding it](https://github.com/ChillerDragon/install/commit/bc6451a15fe98595adda5b2e65ec12b079634ffe) but it did not work. Too lazy to debug the CI now.

**Comment by osalbahr** [comment]
Not sure if I understand what you’re trying to add. Is `./bin` in `PATH` by default on newer macs? I don’t get why `./bin/git` is a thing. Especially that `which -a git` didn’t display `<insert $HOME>/bin/git`. I might look into debugging the CI if I understand the issue

**Comment by ChillerDragon** [comment]
> Not sure if I understand what you’re trying to add. Is `./bin` in `PATH` by default on newer macs? I don’t get why `./bin/git` is a thing. Especially that `which -a git` didn’t display `<insert $HOME>/bin/git`. I might look into debugging the CI if I understand the issue

No it is not in the path by default on newer macs. I recommend reading through the referenced discussions and pullrequests. The installer should not break if someone decides to add ./bin to the PATH.

**Comment by osalbahr** [comment]
I've read through [Unable to install brew: /bin/bash: line 234: bin/git: No such file or directory #4518](https://github.com/orgs/Homebrew/discussions/4518) and it looks like the issue is related to

> For some reason command -v git inside the script is returning ./bin/git

which I don't know why that might happen. Locally:

```
~$ command -v git
/usr/bin/git
```

It seems to be something exclusive to Apple Silicon which I don't have access to, nor know how `command -v git` might behave differently.

I don't know what other "referenced discussions" you might be referring to. If `./bin/git` is not in `PATH` on newer macs, then I have no idea how the installer broke in the discussion I linked above. My question was my best guess since that's what #775 was about.

**Comment by ChillerDragon** [comment]
> 
> Edit: [it looks like they did have `./bin` in `$PATH`.](https://github.com/orgs/Homebrew/discussions/4518#discussioncomment-5953531)

Yes and the install script does a cd /usr first. So it finds /usr/bin/git as ./bin/git

Which breaks when the script later changes directory again
