### PR TITLE
install.sh: do all sudo stuff before first `brew` run

### LINKED ISSUE #999: Avoid sudo invalidation during `brew update` in install.sh
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [x] you carefully read the output and it was not a `git fetch` or other connection issue to GitHub (that Homebrew has no control over)?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I was trying to run the official Homebrew install script in a non-interactive or scripted setup. I pre-warmed the `sudo` credential cache using `sudo -v` before invoking the installer so that all subsequent `sudo` commands in the script would not prompt for a password. This is important when scripting Homebrew installation, such as in CI or local provisioning environments, where no interactive input is possible (or not preferred).

## What happened (include command output)

Despite running `sudo -v` beforehand, the installer still prompted for the `sudo` password again during the final steps. This broke my automated setup.

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

<details>
  <summary>Command output</summary>
  <pre>
===>Downloading and installing Homebrew...
...
/usr/bin/sudo /bin/mkdir -p /etc/paths.d
Password:  ← unexpected prompt here

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew` commands)

```bash
# run sudo beforehand, this will prompt password input
sudo -S echo
# verify the following sudo doesn't need password prompt
sudo -n -v
# password not required for the first few sudo commands, but needed after "Downloading and installing Homebrew..." step
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

## Investigation

My guess is that during the Homebrew installation step ([line 954](https://github.com/Homebrew/install/blob/main/install.sh#L954)-[line 1022](https://github.com/Homebrew/install/blob/main/install.sh#L1022)), the very last step `execute "${HOMEBREW_PREFIX}/bin/brew" "update" "--force" "--quiet"` may invalidate the `sudo` timestamp internally, even when it's pre-warmed. This can cause unexpected password prompts in automation scenarios. Replacing that line with a conditional or skipping it resolved the issue.

## Suggestion:

It is reasonable for brew command to confirm it is not in a sudo session and potentially revoke any previous sudo timestamp. So changing `brew update` is not an option. Instead, I'd suggest adding a conditional environment variable to skip `brew update` during installation such as `SKIP_BREW_UPDATE=1` may be a good idea. We can update brew afterwards without sudo permission.

Another option will be updating brew at the very last step, after all sudo operations are finished.

### PR DESCRIPTION
**Pull request by gromgit**
Otherwise the user gets prompted for password twice.

Closes #999.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
Thanks!

File: install.sh [hunk 1]
```diff
@@ -1019,22 +1019,22 @@ ohai "Downloading and installing Homebrew..."
...
+  then
+    execute_sudo "${MKDIR[@]}" /etc/paths.d
+    echo "${HOMEBREW_PREFIX}/bin" | execute_sudo tee /etc/paths.d/homebrew
+    execute_sudo "${CHOWN[@]}" root:wheel /etc/paths.d/homebrew
+    execute_sudo "${CHMOD[@]}" "a+r" /etc/paths.d/homebrew
+  elif [[ ":${PATH}:" != *":${HOMEBREW_PREFIX}/bin:"* ]]
+  then
+    warn "${HOMEBREW_PREFIX}/bin is not in your PATH.
+    Instructions on how to configure your shell for Homebrew
+    can be found in the 'Next steps' section below."
```
Comment (carlocab) [inline install.sh:1032]: Actually, it might be worth saving this warning for after the `brew update` below, since that can be noisy. Mind moving this warning later?

Comment (gromgit) [reply install.sh:1032]: OK, I'll work it into another PR.
